# Dictionary and Data Formats

This document describes the structure of the main data objects used by Fin-SentiLex.

---

# Overview

The framework relies on three types of objects:

1. Sentiment dictionaries
2. Filing datasets
3. SVM evaluation datasets

Understanding these structures makes it easier to build new dictionaries or apply the framework to new financial datasets.

---

# Sentiment Dictionaries

The central object in Fin-SentiLex is the sentiment dictionary.

Each word is associated with a collection of sentiment values and optimization statistics.

A typical dictionary entry has the form:

```python
dictionary[word] = {
    'pos': ...,
    'neg': ...,
    'mp': ...,
    'mn': ...,
    'vp': ...,
    'vn': ...,
    'ndocs': ...
}
```

---

# Dictionary Fields

## Sentiment Values

```python
dictionary[word]['pos']
dictionary[word]['neg']
```

These represent the learned positive and negative sentiment strengths associated with a word.

For example:

```python
dictionary['growth']['pos']
dictionary['growth']['neg']
```

Words associated with positive outcomes tend to develop larger positive scores, while words associated with negative outcomes tend to develop larger negative scores.

---

## Adam Optimizer Parameters

The neural-network training process stores optimizer state information for each word.

### First Moments

```python
dictionary[word]['mp']
dictionary[word]['mn']
```

Used by the Adam optimizer to track moving averages of gradients.

### Second Moments

```python
dictionary[word]['vp']
dictionary[word]['vn']
```

Used by the Adam optimizer to track moving averages of squared gradients.

These values are updated during neural-network training.

---

## Document Frequency

```python
dictionary[word]['ndocs']
```

The number of documents containing the word.

This value is used when constructing TF-IDF weighted document representations.

---

# Dictionary Files

The repository uses several dictionary files.

## Initial Dictionary

```text
dictionary_filtered.pckl
```

Starting dictionary used by the neural-network models.

---

## Classification Dictionary

```text
dictionary_classificationNN.pckl
```

Generated by:

```bash
python classificationNN.py
```

Optimized for binary prediction tasks.

---

## Regression Dictionary

```text
dictionary_regressionNN.pckl
```

Generated by:

```bash
python regressionNN.py
```

Optimized for continuous prediction tasks.

---

## Benchmark Dictionary

```text
dictionary_benchNN.pckl
```

Baseline neural-network dictionary used during benchmarking.

---

## Loughran-McDonald Dictionary

```text
Loughran_McDonald_dict.pckl
```

Reference financial sentiment lexicon used for comparison.

---

# Filing Dataset Format

The neural-network models operate on filing objects stored in yearly datasets.

Example:

```text
200710X_final.pckl
201010X_final.pckl
201810X_final.pckl
```

Each dataset contains a collection of filing observations.

The training scripts directly access:

```python
item[4]
item[5]
item[-1]
```

indicating that each filing record contains at least:

| Element | Description |
|----------|-------------|
| item[4] | Binary classification target |
| item[5] | Continuous regression target |
| item[-1] | Filing text |

---

# Text Field

The filing text is expected to be stored as:

```python
item[-1]
```

and should contain the raw text extracted from the SEC filing.

Example:

```python
text = item[-1]
```

The text is subsequently cleaned using:

```python
f10X.cleanText()
```

before feature extraction.

---

# Neural-Network Inputs

For each filing, words found in the dictionary are converted into:

```text
[positive_score,
 negative_score]
```

pairs.

These values are weighted using TF-IDF and aggregated to create:

```text
[positive_document_score,
 negative_document_score]
```

which form the input to the neural-network models.

---

# SVM Dataset Format

The SVM framework does not operate directly on filing text.

Instead, dictionary scores are first converted into feature matrices.

The resulting data are stored as:

```text
train_final.pckl
test_final.pckl
```

and contain one matrix for each evaluated dictionary.

Example:

```python
train['Loughran']
train['Classification']
train['Regression']
```

---

# Feature Matrix Structure

In the current implementation:

```python
X = train[name][:,2:13]
```

defines the input features.

Target variables are stored as:

```python
y = train[name][:,13:]
```

The exact interpretation of each column depends on the output generated by:

```python
fSVM.getScores()
```

---

# Benchmark Dictionary Set

The standard benchmark compares four dictionaries:

```python
[
    'Loughran',
    'Benchmark',
    'Classification',
    'Regression'
]
```

These correspond to:

| Name | Dictionary |
|--------|-------------|
| Loughran | Loughran-McDonald |
| Benchmark | Baseline NN dictionary |
| Classification | Classification-trained dictionary |
| Regression | Regression-trained dictionary |

Additional dictionaries can easily be added to this benchmark framework.

---

# Adding a New Dictionary

A new dictionary can be introduced by loading it and appending it to the benchmark list.

Example:

```python
myDict = fd.loadFile(
    drive + 'dictionary_my_model.pckl'
)

dictionaries.append(myDict)

dict_names.append(
    'MyModel'
)
```

The new dictionary will then be processed automatically by:

```python
SVMDataset()
forecastSVM()
resultsForecasts()
```

allowing direct comparison with the existing benchmarks.
